baseURL = "/"
languageCode = "en-gb"
title = "Bless Your Heart"

enableRobotsTXT = true
disableAliases = true

googleAnalytics = "UA-118254944-1"


[params]
  description = "We are a mother daughter team specializing in farmhouse and french country decor and is passionate about making the vision for your home come true!"
  facebook = "https://www.facebook.com/blessyourheartofal/"
  instagram = "https://www.instagram.com/blessyourheartofal/"
  pinterest = "https://www.pinterest.com/blessyourhearto/"

# add redirects/headers
[outputs]
home = ["HTML", "RSS", "REDIRECTS", "HEADERS"]

# remove .{ext} from text/netlify
[mediaTypes."text/netlify"]
suffix = ""
delimiter = ""

# add output format for netlify _redirects
[outputFormats.REDIRECTS]
mediatype = "text/netlify"
baseName = "_redirects"
isPlainText = true
notAlternative = true

# add output format for netlify _headers
[outputFormats.HEADERS]
mediatype = "text/netlify"
baseName = "_headers"
isPlainText = true
notAlternative = true

